//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 14:09:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ProjectManagement.Domain;
using ProjectManagement.DLL.ORM;

namespace ProjectManagement.DLL
{

    /// <summary>
    /// Assembler for <see cref="CreditLimit"/> and <see cref="CreditLimitDTO"/>.
    /// </summary>
    public static partial class CreditLimitAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="CreditLimitDTO"/> converted from <see cref="CreditLimit"/>.</param>
        static partial void OnDTO(this CreditLimit entity, CreditLimitDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="CreditLimit"/> converted from <see cref="CreditLimitDTO"/>.</param>
        static partial void OnEntity(this CreditLimitDTO dto, CreditLimit entity);

        /// <summary>
        /// Converts this instance of <see cref="CreditLimitDTO"/> to an instance of <see cref="CreditLimit"/>.
        /// </summary>
        /// <param name="dto"><see cref="CreditLimitDTO"/> to convert.</param>
        public static CreditLimit ToEntity(this CreditLimitDTO dto)
        {
            if (dto == null) return null;

            var entity = new CreditLimit();

            entity.Sup_id = dto.Sup_id;
            entity.Balance = dto.Balance;
            entity.CreditDays = dto.CreditDays;
            entity.CreditAmmount = dto.CreditAmmount;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="CreditLimit"/> to an instance of <see cref="CreditLimitDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="CreditLimit"/> to convert.</param>
        public static CreditLimitDTO ToDTO(this CreditLimit entity)
        {
            if (entity == null) return null;

            var dto = new CreditLimitDTO();

            dto.Sup_id = entity.Sup_id;
            dto.Balance = entity.Balance;
            dto.CreditDays = entity.CreditDays;
            dto.CreditAmmount = entity.CreditAmmount;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="CreditLimitDTO"/> to an instance of <see cref="CreditLimit"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<CreditLimit> ToEntities(this IEnumerable<CreditLimitDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="CreditLimit"/> to an instance of <see cref="CreditLimitDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<CreditLimitDTO> ToDTOs(this IEnumerable<CreditLimit> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
