//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 14:09:29
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ProjectManagement.Domain;
using ProjectManagement.DLL.ORM;

namespace ProjectManagement.DLL
{

    /// <summary>
    /// Assembler for <see cref="QtyMaterial"/> and <see cref="QtyMaterialDTO"/>.
    /// </summary>
    public static partial class QtyMaterialAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="QtyMaterialDTO"/> converted from <see cref="QtyMaterial"/>.</param>
        static partial void OnDTO(this QtyMaterial entity, QtyMaterialDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="QtyMaterial"/> converted from <see cref="QtyMaterialDTO"/>.</param>
        static partial void OnEntity(this QtyMaterialDTO dto, QtyMaterial entity);

        /// <summary>
        /// Converts this instance of <see cref="QtyMaterialDTO"/> to an instance of <see cref="QtyMaterial"/>.
        /// </summary>
        /// <param name="dto"><see cref="QtyMaterialDTO"/> to convert.</param>
        public static QtyMaterial ToEntity(this QtyMaterialDTO dto)
        {
            if (dto == null) return null;

            var entity = new QtyMaterial();

            entity.Reg_id = dto.Reg_id;
            entity.Mat_id = dto.Mat_id;
            entity.Sup_id = dto.Sup_id;
            entity.Ddate = dto.Ddate;
            entity.Challan_No = dto.Challan_No;
            entity.Disp = dto.Disp;
            entity.Qty = dto.Qty;
            entity.Rate = dto.Rate;
            entity.Ammount = dto.Ammount;
            entity.Unit = dto.Unit;
            entity.Proj_Name = dto.Proj_Name;
            entity.Bill_No = dto.Bill_No;
            entity.Bill_Rate = dto.Bill_Rate;
            entity.Bil_Ent = dto.Bil_Ent;
            entity.Valid = dto.Valid;
            entity.Bill_Date = dto.Bill_Date;
            entity.Bill_Ent_No = dto.Bill_Ent_No;
            entity.GuidQty = dto.GuidQty;
            entity.userss = dto.userss;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="QtyMaterial"/> to an instance of <see cref="QtyMaterialDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="QtyMaterial"/> to convert.</param>
        public static QtyMaterialDTO ToDTO(this QtyMaterial entity)
        {
            if (entity == null) return null;

            var dto = new QtyMaterialDTO();

            dto.Reg_id = entity.Reg_id;
            dto.Mat_id = entity.Mat_id;
            dto.Sup_id = entity.Sup_id;
            dto.Ddate = entity.Ddate;
            dto.Challan_No = entity.Challan_No;
            dto.Disp = entity.Disp;
            dto.Qty = entity.Qty;
            dto.Rate = entity.Rate;
            dto.Ammount = entity.Ammount;
            dto.Unit = entity.Unit;
            dto.Proj_Name = entity.Proj_Name;
            dto.Bill_No = entity.Bill_No;
            dto.Bill_Rate = entity.Bill_Rate;
            dto.Bil_Ent = entity.Bil_Ent;
            dto.Valid = entity.Valid;
            dto.Bill_Date = entity.Bill_Date;
            dto.Bill_Ent_No = entity.Bill_Ent_No;
            dto.GuidQty = entity.GuidQty;
            dto.userss = entity.userss;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="QtyMaterialDTO"/> to an instance of <see cref="QtyMaterial"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<QtyMaterial> ToEntities(this IEnumerable<QtyMaterialDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="QtyMaterial"/> to an instance of <see cref="QtyMaterialDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<QtyMaterialDTO> ToDTOs(this IEnumerable<QtyMaterial> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
