//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/03/01 - 20:26:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ProjectManagement.Domain;
using ProjectManagement.DLL.ORM;

namespace ProjectManagement.DLL
{

    /// <summary>
    /// Assembler for <see cref="tblAccountType"/> and <see cref="tblAccountTypeDTO"/>.
    /// </summary>
    public static partial class tblAccountTypeAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblAccountTypeDTO"/> converted from <see cref="tblAccountType"/>.</param>
        static partial void OnDTO(this tblAccountType entity, tblAccountTypeDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblAccountType"/> converted from <see cref="tblAccountTypeDTO"/>.</param>
        static partial void OnEntity(this tblAccountTypeDTO dto, tblAccountType entity);

        /// <summary>
        /// Converts this instance of <see cref="tblAccountTypeDTO"/> to an instance of <see cref="tblAccountType"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblAccountTypeDTO"/> to convert.</param>
        public static tblAccountType ToEntity(this tblAccountTypeDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblAccountType();

            entity.AccountTypeId = dto.AccountTypeId;
            entity.TypeName = dto.TypeName;
            entity.Childof = dto.Childof;
            entity.IsDisplay = dto.IsDisplay;
            entity.ClosingBalance = dto.ClosingBalance;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblAccountType"/> to an instance of <see cref="tblAccountTypeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblAccountType"/> to convert.</param>
        public static tblAccountTypeDTO ToDTO(this tblAccountType entity)
        {
            if (entity == null) return null;

            var dto = new tblAccountTypeDTO();

            dto.AccountTypeId = entity.AccountTypeId;
            dto.TypeName = entity.TypeName;
            dto.Childof = entity.Childof;
            dto.IsDisplay = entity.IsDisplay;
            dto.ClosingBalance = entity.ClosingBalance;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblAccountTypeDTO"/> to an instance of <see cref="tblAccountType"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblAccountType> ToEntities(this IEnumerable<tblAccountTypeDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblAccountType"/> to an instance of <see cref="tblAccountTypeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblAccountTypeDTO> ToDTOs(this IEnumerable<tblAccountType> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
