//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/03/01 - 20:26:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ProjectManagement.Domain;
using ProjectManagement.DLL.ORM;

namespace ProjectManagement.DLL
{

    /// <summary>
    /// Assembler for <see cref="tblMemberType"/> and <see cref="tblMemberTypeDTO"/>.
    /// </summary>
    public static partial class tblMemberTypeAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblMemberTypeDTO"/> converted from <see cref="tblMemberType"/>.</param>
        static partial void OnDTO(this tblMemberType entity, tblMemberTypeDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblMemberType"/> converted from <see cref="tblMemberTypeDTO"/>.</param>
        static partial void OnEntity(this tblMemberTypeDTO dto, tblMemberType entity);

        /// <summary>
        /// Converts this instance of <see cref="tblMemberTypeDTO"/> to an instance of <see cref="tblMemberType"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblMemberTypeDTO"/> to convert.</param>
        public static tblMemberType ToEntity(this tblMemberTypeDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblMemberType();

            entity.MemberTypeId = dto.MemberTypeId;
            entity.TypeName = dto.TypeName;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblMemberType"/> to an instance of <see cref="tblMemberTypeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblMemberType"/> to convert.</param>
        public static tblMemberTypeDTO ToDTO(this tblMemberType entity)
        {
            if (entity == null) return null;

            var dto = new tblMemberTypeDTO();

            dto.MemberTypeId = entity.MemberTypeId;
            dto.TypeName = entity.TypeName;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblMemberTypeDTO"/> to an instance of <see cref="tblMemberType"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblMemberType> ToEntities(this IEnumerable<tblMemberTypeDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblMemberType"/> to an instance of <see cref="tblMemberTypeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblMemberTypeDTO> ToDTOs(this IEnumerable<tblMemberType> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
