//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/03/01 - 20:26:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using ProjectManagement.Domain;
using ProjectManagement.DLL.ORM;

namespace ProjectManagement.DLL
{

    /// <summary>
    /// Assembler for <see cref="tblMaterialGroup"/> and <see cref="tblMaterialGroupDTO"/>.
    /// </summary>
    public static partial class tblMaterialGroupAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblMaterialGroupDTO"/> converted from <see cref="tblMaterialGroup"/>.</param>
        static partial void OnDTO(this tblMaterialGroup entity, tblMaterialGroupDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblMaterialGroup"/> converted from <see cref="tblMaterialGroupDTO"/>.</param>
        static partial void OnEntity(this tblMaterialGroupDTO dto, tblMaterialGroup entity);

        /// <summary>
        /// Converts this instance of <see cref="tblMaterialGroupDTO"/> to an instance of <see cref="tblMaterialGroup"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblMaterialGroupDTO"/> to convert.</param>
        public static tblMaterialGroup ToEntity(this tblMaterialGroupDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblMaterialGroup();

            entity.MaterialGroupId = dto.MaterialGroupId;
            entity.GroupName = dto.GroupName;
            entity.Description = dto.Description;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblMaterialGroup"/> to an instance of <see cref="tblMaterialGroupDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblMaterialGroup"/> to convert.</param>
        public static tblMaterialGroupDTO ToDTO(this tblMaterialGroup entity)
        {
            if (entity == null) return null;

            var dto = new tblMaterialGroupDTO();

            dto.MaterialGroupId = entity.MaterialGroupId;
            dto.GroupName = entity.GroupName;
            dto.Description = entity.Description;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblMaterialGroupDTO"/> to an instance of <see cref="tblMaterialGroup"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblMaterialGroup> ToEntities(this IEnumerable<tblMaterialGroupDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblMaterialGroup"/> to an instance of <see cref="tblMaterialGroupDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblMaterialGroupDTO> ToDTOs(this IEnumerable<tblMaterialGroup> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
