//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditLimit
    {
        public string Sup_id { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<int> CreditDays { get; set; }
        public Nullable<double> CreditAmmount { get; set; }
    }
}
