//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReport
    {
        public string Rptid { get; set; }
        public System.DateTime ddate { get; set; }
        public Nullable<int> cement { get; set; }
        public Nullable<int> steel { get; set; }
        public Nullable<int> sand { get; set; }
        public Nullable<int> kapchi { get; set; }
        public Nullable<int> Bricks { get; set; }
        public Nullable<int> tile { get; set; }
        public Nullable<int> deptSkill { get; set; }
        public Nullable<int> deptUnskil { get; set; }
        public Nullable<int> centSkill { get; set; }
        public Nullable<int> centunskill { get; set; }
        public Nullable<int> BrSkill { get; set; }
        public Nullable<int> Brunskill { get; set; }
        public Nullable<int> PlastSkill { get; set; }
        public Nullable<int> Plastunskill { get; set; }
        public Nullable<int> FloorSkill { get; set; }
        public Nullable<int> Floorunskill { get; set; }
        public Nullable<int> ColourSkill { get; set; }
        public Nullable<int> Plumbingskill { get; set; }
        public Nullable<int> OtherSkill { get; set; }
        public Nullable<int> otherunskill { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Lock { get; set; }
        public Nullable<System.DateTime> LockingDate { get; set; }
    }
}
