//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupBySupplier
    {
        public int GrpIdSupplier { get; set; }
        public string GroupSupplierName { get; set; }
        public Nullable<int> childOf { get; set; }
        public Nullable<bool> Display { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
    }
}
