//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupByItem
    {
        public string GrpIdItem { get; set; }
        public string GroupItemName { get; set; }
        public string GuIdGroup { get; set; }
        public string ChildOF { get; set; }
    }
}
