//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_store
    {
        public System.DateTime timemark { get; set; }
        public string table_name { get; set; }
        public string pk_date_src { get; set; }
        public string pk_date_dest { get; set; }
        public short record_state { get; set; }
    }
}
