//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mat_AccountTwo
    {
        public string Ent_No { get; set; }
        public int VrNo { get; set; }
        public string Mode_Pay_Rec { get; set; }
        public string Rec_Pay { get; set; }
        public Nullable<double> Ammount { get; set; }
        public Nullable<System.DateTime> Ddate { get; set; }
        public string Disp { get; set; }
        public string From_Account { get; set; }
        public string To_Account { get; set; }
        public string Hand_Group { get; set; }
        public Nullable<double> Kwat { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Hand { get; set; }
        public string SetViewOne { get; set; }
        public Nullable<bool> Freezed { get; set; }
        public Nullable<bool> IsEntryOnly { get; set; }
        public string GuidAC { get; set; }
        public Nullable<System.DateTime> CurDate { get; set; }
        public Nullable<bool> Hide { get; set; }
        public string ChqNo { get; set; }
        public string ChqDrawn { get; set; }
        public string Userss { get; set; }
        public string fy { get; set; }
    }
}
