//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public string Mat_id { get; set; }
        public string Mat_Name { get; set; }
        public string Mat_Unit { get; set; }
        public Nullable<double> Basic_Rate { get; set; }
        public string GroupId { get; set; }
        public string GuIdMaterial { get; set; }
        public string userss { get; set; }
    }
}
