//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectManagementSQLDatabaseEntities : DbContext
    {
        public ProjectManagementSQLDatabaseEntities()
            : base("name=ProjectManagementSQLDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblEntityMaster> tblEntityMasters { get; set; }
        public DbSet<tblMember> tblMembers { get; set; }
        public DbSet<tblMemberPermission> tblMemberPermissions { get; set; }
        public DbSet<tblMemberType> tblMemberTypes { get; set; }
        public DbSet<tblProject> tblProjects { get; set; }
    }
}
