//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class QtyMaterial
    {
        public string Reg_id { get; set; }
        public string Mat_id { get; set; }
        public string Sup_id { get; set; }
        public Nullable<System.DateTime> Ddate { get; set; }
        public Nullable<int> Challan_No { get; set; }
        public string Disp { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Ammount { get; set; }
        public string Unit { get; set; }
        public string Proj_Name { get; set; }
        public Nullable<short> Bill_No { get; set; }
        public Nullable<double> Bill_Rate { get; set; }
        public Nullable<bool> Bil_Ent { get; set; }
        public Nullable<bool> Valid { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public string Bill_Ent_No { get; set; }
        public string GuidQty { get; set; }
        public string userss { get; set; }
    }
}
