//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public string Sup_id { get; set; }
        public string NameiS { get; set; }
        public string AddiS { get; set; }
        public string City { get; set; }
        public Nullable<double> OpBalance { get; set; }
        public string Sup_Ph { get; set; }
        public Nullable<int> creditday { get; set; }
        public Nullable<double> creditammount { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string GuIdSup { get; set; }
        public Nullable<short> share { get; set; }
        public Nullable<System.DateTime> CutDate { get; set; }
        public string Adding { get; set; }
        public Nullable<double> IntRates { get; set; }
        public Nullable<bool> AutoUpdate { get; set; }
        public string alias { get; set; }
        public string userss { get; set; }
        public string childof { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> CashBankBalance { get; set; }
    }
}
