//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountType
    {
        public int AccountTypeId { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> Childof { get; set; }
        public Nullable<bool> IsDisplay { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
    }
}
