//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        public tblCompany()
        {
            this.tblMaterials = new HashSet<tblMaterial>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string ContactDetails { get; set; }
        public string AboutUs { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<tblMaterial> tblMaterials { get; set; }
    }
}
