//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaterial
    {
        public int MaterialId { get; set; }
        public int MaterialGroupId { get; set; }
        public string Name { get; set; }
        public double BasicRate { get; set; }
        public double OpeningStock { get; set; }
        public int MemberId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime CreationDateTime { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblMaterialGroup tblMaterialGroup { get; set; }
        public virtual tblMember tblMember { get; set; }
    }
}
