//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.DLL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMemberPermission
    {
        public int MemberPermissionId { get; set; }
        public int PermisisonId { get; set; }
        public int MemberId { get; set; }
    
        public virtual tblPermissionMaster tblPermissionMaster { get; set; }
        public virtual tblMember tblMember { get; set; }
    }
}
