//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-12 - 18:32:08
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblChangePassword
    {
        [DataMember()]
        [Required(ErrorMessage = "Please enter password.")]
        public String OldPassword { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "Please enter new password.")]
        public String NewPassword { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "Please enter re-type password.")]
        public String ReTypePassword { get; set; }
    }
}
