//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-12 - 18:32:08
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblReportDTO
    {
        public string TransactionType { get; set; }
        public string Supplier1Id { get; set; }
        public string Supplier1TypeName { get; set; }
        public string Supplier2Id { get; set; }
        public string EntryId { get; set; }
        public int VrNo { get; set; }
        public string ModePaymentReceipt { get; set; }
        public string RecPay { get; set; }
        public double? Amount { get; set; }
        public Nullable<DateTime> DDate { get; set; }
        public string Description { get; set; }
        public string FromAccount { get; set; }
        public string ToAccount { get; set; }
        public string HandGroup { get; set; }
        public double? Kwat { get; set; }
        public double? Discount { get; set; }
        public double? Hand { get; set; }
        public string SetViewOne { get; set; }
        public bool? IsEntryOnly { get; set; }
        public string GuidAC { get; set; }
        public Nullable<DateTime> CurDate { get; set; }
        public bool? Hide { get; set; }
        public string ChequeNo { get; set; }
        public string Users { get; set; }
        public string FiscalYear { get; set; }
    }
}
