//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-12 - 18:32:08
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using System.Web.Mvc;

namespace ProjectManagement.Domain
{
    public partial class tblReportModelDTO
    {
        public List<SupplierDTO> SupplierList { get; set; }
        public List<tblReportDTO> ReportData { get; set; }
        public List<SelectListItem> YearList { get; set; }

    }
}
