//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-12 - 18:32:08
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class TrialReportDTO
    {
        public TrialReportDTO()
        {
            
        }

        public string SupId { get; set; }
        public string ChildOf { get; set; }
        public double Balance { get; set; }
        public string NameiS { get; set; }
        public string GroupSupplierName { get; set; }
    }
}
