//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 14:09:20
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class CreditLimitDTO
    {
        [DataMember()]
        public String Sup_id { get; set; }

        [DataMember()]
        public Nullable<Double> Balance { get; set; }

        [DataMember()]
        public Nullable<Int32> CreditDays { get; set; }

        [DataMember()]
        public Nullable<Double> CreditAmmount { get; set; }

        public CreditLimitDTO()
        {
        }

        public CreditLimitDTO(String sup_id, Nullable<Double> balance, Nullable<Int32> creditDays, Nullable<Double> creditAmmount)
        {
			this.Sup_id = sup_id;
			this.Balance = balance;
			this.CreditDays = creditDays;
			this.CreditAmmount = creditAmmount;
        }
    }
}
