//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 14:09:21
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class GroupByItemDTO
    {
        [DataMember()]
        public String GrpIdItem { get; set; }

        [DataMember()]
        [Required]
        public String GroupItemName { get; set; }

        [DataMember()]
        public String GuIdGroup { get; set; }

        [DataMember()]
        public String ChildOF { get; set; }

        public GroupByItemDTO()
        {
        }

        public GroupByItemDTO(String grpIdItem, String groupItemName, String guIdGroup, String childOF)
        {
			this.GrpIdItem = grpIdItem;
			this.GroupItemName = groupItemName;
			this.GuIdGroup = guIdGroup;
			this.ChildOF = childOF;
        }
    }
}
