//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 14:09:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class history_storeDTO
    {
        [DataMember()]
        public DateTime timemark { get; set; }

        [DataMember()]
        public String table_name { get; set; }

        [DataMember()]
        public String pk_date_src { get; set; }

        [DataMember()]
        public String pk_date_dest { get; set; }

        [DataMember()]
        public Int16 record_state { get; set; }

        public history_storeDTO()
        {
        }

        public history_storeDTO(DateTime timemark, String table_name, String pk_date_src, String pk_date_dest, Int16 record_state)
        {
			this.timemark = timemark;
			this.table_name = table_name;
			this.pk_date_src = pk_date_src;
			this.pk_date_dest = pk_date_dest;
			this.record_state = record_state;
        }
    }
}
