//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 14:09:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class Mat_AccountTwoDTO
    {
        [DataMember()]
        public String Ent_No { get; set; }

        [DataMember()]
        public Int32 VrNo { get; set; }

        [DataMember()]
        public String Mode_Pay_Rec { get; set; }

        [DataMember()]
        public String Rec_Pay { get; set; }

        [DataMember()]
        public Nullable<Double> Ammount { get; set; }

        [DataMember()]
        public Nullable<DateTime> Ddate { get; set; }

        [DataMember()]
        public String Disp { get; set; }

        [DataMember()]
        public String From_Account { get; set; }

        [DataMember()]
        public String To_Account { get; set; }

        [DataMember()]
        public String Hand_Group { get; set; }

        [DataMember()]
        public Nullable<Double> Kwat { get; set; }

        [DataMember()]
        public Nullable<Double> Discount { get; set; }

        [DataMember()]
        public Nullable<Double> Hand { get; set; }

        [DataMember()]
        public String SetViewOne { get; set; }

        [DataMember()]
        public Nullable<Boolean> Freezed { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsEntryOnly { get; set; }

        [DataMember()]
        public String GuidAC { get; set; }

        [DataMember()]
        public Nullable<DateTime> CurDate { get; set; }

        [DataMember()]
        public Nullable<Boolean> Hide { get; set; }

        [DataMember()]
        public String ChqNo { get; set; }

        [DataMember()]
        public String ChqDrawn { get; set; }

        [DataMember()]
        public String Userss { get; set; }

        [DataMember()]
        public String fy { get; set; }

        public Mat_AccountTwoDTO()
        {
        }

        public Mat_AccountTwoDTO(String ent_No, Int32 vrNo, String mode_Pay_Rec, String rec_Pay, Nullable<Double> ammount, Nullable<DateTime> ddate, String disp, String from_Account, String to_Account, String hand_Group, Nullable<Double> kwat, Nullable<Double> discount, Nullable<Double> hand, String setViewOne, Nullable<Boolean> freezed, Nullable<Boolean> isEntryOnly, String guidAC, Nullable<DateTime> curDate, Nullable<Boolean> hide, String chqNo, String chqDrawn, String userss, String fy)
        {
			this.Ent_No = ent_No;
			this.VrNo = vrNo;
			this.Mode_Pay_Rec = mode_Pay_Rec;
			this.Rec_Pay = rec_Pay;
			this.Ammount = ammount;
			this.Ddate = ddate;
			this.Disp = disp;
			this.From_Account = from_Account;
			this.To_Account = to_Account;
			this.Hand_Group = hand_Group;
			this.Kwat = kwat;
			this.Discount = discount;
			this.Hand = hand;
			this.SetViewOne = setViewOne;
			this.Freezed = freezed;
			this.IsEntryOnly = isEntryOnly;
			this.GuidAC = guidAC;
			this.CurDate = curDate;
			this.Hide = hide;
			this.ChqNo = chqNo;
			this.ChqDrawn = chqDrawn;
			this.Userss = userss;
			this.fy = fy;
        }
    }
}
