//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 14:09:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class MaterialDTO
    {
        [DataMember()]
        public String Mat_id { get; set; }

        [DataMember()]
        public String Mat_Name { get; set; }

        [DataMember()]
        public String Mat_Unit { get; set; }

        [DataMember()]
        public Nullable<Double> Basic_Rate { get; set; }

        [DataMember()]
        public String GroupId { get; set; }

        [DataMember()]
        public String GuIdMaterial { get; set; }

        [DataMember()]
        public String userss { get; set; }

    }
}
