//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 14:09:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class QtyMaterialDTO
    {
        [DataMember()]
        public String Reg_id { get; set; }

        [DataMember()]
        public String Mat_id { get; set; }

        [DataMember()]
        public String Sup_id { get; set; }

        [DataMember()]
        public Nullable<DateTime> Ddate { get; set; }

        [Required(ErrorMessage="Please select date.")]
        public string DdateString { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "Please enter challan no.")]
        public Nullable<Int32> Challan_No { get; set; }

        [DataMember()]
        public String Disp { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "Please enter quantity.")]
        public Nullable<Double> Qty { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "Please enter rate.")]
        public Nullable<Double> Rate { get; set; }

        [DataMember()]
        public Nullable<Double> Ammount { get; set; }

        [DataMember()]
        public String Unit { get; set; }

        [DataMember()]
        public String Proj_Name { get; set; }

        [DataMember()]
        public Nullable<Int16> Bill_No { get; set; }

        [DataMember()]
        public Nullable<Double> Bill_Rate { get; set; }

        [DataMember()]
        public Nullable<Boolean> Bil_Ent { get; set; }

        [DataMember()]
        public Nullable<Boolean> Valid { get; set; }

        [DataMember()]
        public Nullable<DateTime> Bill_Date { get; set; }

        [DataMember()]
        public String Bill_Ent_No { get; set; }

        [DataMember()]
        public String GuidQty { get; set; }

        [DataMember()]
        public String userss { get; set; }

        public string MaterialName { get; set; }

        public string SupplierName { get; set; }

        public List<MaterialDTO> MaterialList { get; set; }

        public List<SupplierDTO> SupplierList { get; set; }

        public List<string> UnitTypeList { get; set; }
    }
}
