//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 14:09:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class QtyMaterialDTO
    {
        [DataMember()]
        public String Reg_id { get; set; }

        [DataMember()]
        public String Mat_id { get; set; }

        [DataMember()]
        public String Sup_id { get; set; }

        [DataMember()]
        public Nullable<DateTime> Ddate { get; set; }

        [DataMember()]
        public Nullable<Int32> Challan_No { get; set; }

        [DataMember()]
        public String Disp { get; set; }

        [DataMember()]
        public Nullable<Double> Qty { get; set; }

        [DataMember()]
        public Nullable<Double> Rate { get; set; }

        [DataMember()]
        public Nullable<Double> Ammount { get; set; }

        [DataMember()]
        public String Unit { get; set; }

        [DataMember()]
        public String Proj_Name { get; set; }

        [DataMember()]
        public Nullable<Int16> Bill_No { get; set; }

        [DataMember()]
        public Nullable<Double> Bill_Rate { get; set; }

        [DataMember()]
        public Nullable<Boolean> Bil_Ent { get; set; }

        [DataMember()]
        public Nullable<Boolean> Valid { get; set; }

        [DataMember()]
        public Nullable<DateTime> Bill_Date { get; set; }

        [DataMember()]
        public String Bill_Ent_No { get; set; }

        [DataMember()]
        public String GuidQty { get; set; }

        [DataMember()]
        public String userss { get; set; }

        public QtyMaterialDTO()
        {
        }

        public QtyMaterialDTO(String reg_id, String mat_id, String sup_id, Nullable<DateTime> ddate, Nullable<Int32> challan_No, String disp, Nullable<Double> qty, Nullable<Double> rate, Nullable<Double> ammount, String unit, String proj_Name, Nullable<Int16> bill_No, Nullable<Double> bill_Rate, Nullable<Boolean> bil_Ent, Nullable<Boolean> valid, Nullable<DateTime> bill_Date, String bill_Ent_No, String guidQty, String userss)
        {
			this.Reg_id = reg_id;
			this.Mat_id = mat_id;
			this.Sup_id = sup_id;
			this.Ddate = ddate;
			this.Challan_No = challan_No;
			this.Disp = disp;
			this.Qty = qty;
			this.Rate = rate;
			this.Ammount = ammount;
			this.Unit = unit;
			this.Proj_Name = proj_Name;
			this.Bill_No = bill_No;
			this.Bill_Rate = bill_Rate;
			this.Bil_Ent = bil_Ent;
			this.Valid = valid;
			this.Bill_Date = bill_Date;
			this.Bill_Ent_No = bill_Ent_No;
			this.GuidQty = guidQty;
			this.userss = userss;
        }
    }
}
