//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 14:09:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class SupplierDTO
    {
        [DataMember()]
        public String Sup_id { get; set; }

        [DataMember()]
        public String NameiS { get; set; }

        [DataMember()]
        public String AddiS { get; set; }

        [DataMember()]
        public String City { get; set; }

        [DataMember()]
        public Nullable<Double> OpBalance { get; set; }

        [DataMember()]
        public String Sup_Ph { get; set; }

        [DataMember()]
        public Nullable<Int32> creditday { get; set; }

        [DataMember()]
        public Nullable<Double> creditammount { get; set; }

        [DataMember()]
        public Nullable<Int32> GroupId { get; set; }

        [DataMember()]
        public String GuIdSup { get; set; }

        [DataMember()]
        public Nullable<Int16> share { get; set; }

        [DataMember()]
        public Nullable<DateTime> CutDate { get; set; }

        [DataMember()]
        public String Adding { get; set; }

        [DataMember()]
        public Nullable<Double> IntRates { get; set; }

        [DataMember()]
        public Nullable<Boolean> AutoUpdate { get; set; }

        [DataMember()]
        public String alias { get; set; }

        [DataMember()]
        public String userss { get; set; }

        [DataMember()]
        public String childof { get; set; }

        [DataMember()]
        public Double Balance { get; set; }

        [DataMember()]
        public Double CashBankBalance { get; set; }

        public SupplierDTO()
        {
        }

        public SupplierDTO(String sup_id, String nameiS, String addiS, String city, Nullable<Double> opBalance, String sup_Ph, Nullable<Int32> creditday, Nullable<Double> creditammount, Nullable<Int32> groupId, String guIdSup, Nullable<Int16> share, Nullable<DateTime> cutDate, String adding, Nullable<Double> intRates, Nullable<Boolean> autoUpdate, String alias, String userss, String childof, Double balance, Double cashBankBalance)
        {
			this.Sup_id = sup_id;
			this.NameiS = nameiS;
			this.AddiS = addiS;
			this.City = city;
			this.OpBalance = opBalance;
			this.Sup_Ph = sup_Ph;
			this.creditday = creditday;
			this.creditammount = creditammount;
			this.GroupId = groupId;
			this.GuIdSup = guIdSup;
			this.share = share;
			this.CutDate = cutDate;
			this.Adding = adding;
			this.IntRates = intRates;
			this.AutoUpdate = autoUpdate;
			this.alias = alias;
			this.userss = userss;
			this.childof = childof;
			this.Balance = balance;
			this.CashBankBalance = cashBankBalance;
        }
    }
}
