//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/03/01 - 20:26:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblAccountTypeDTO
    {
        [DataMember()]
        public Int32 AccountTypeId { get; set; }

        [DataMember()]
        public String TypeName { get; set; }

        [DataMember()]
        public Nullable<Int32> Childof { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDisplay { get; set; }

        [DataMember()]
        public Nullable<Double> ClosingBalance { get; set; }

        public tblAccountTypeDTO()
        {
        }

        public tblAccountTypeDTO(Int32 accountTypeId, String typeName, Nullable<Int32> childof, Nullable<Boolean> isDisplay, Nullable<Double> closingBalance)
        {
			this.AccountTypeId = accountTypeId;
			this.TypeName = typeName;
			this.Childof = childof;
			this.IsDisplay = isDisplay;
			this.ClosingBalance = closingBalance;
        }
    }
}
