//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/03/01 - 20:26:20
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblCompanyDTO
    {
        [DataMember()]
        public Int32 CompanyId { get; set; }

        [DataMember()]
        public String CompanyName { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        public String ContactDetails { get; set; }

        [DataMember()]
        public String AboutUs { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public List<Int32> tblMaterials_MaterialId { get; set; }

        public tblCompanyDTO()
        {
        }

        public tblCompanyDTO(Int32 companyId, String companyName, String address, String contactDetails, String aboutUs, Nullable<DateTime> creationDateTime, Nullable<Boolean> isActive, List<Int32> tblMaterials_MaterialId)
        {
			this.CompanyId = companyId;
			this.CompanyName = companyName;
			this.Address = address;
			this.ContactDetails = contactDetails;
			this.AboutUs = aboutUs;
			this.CreationDateTime = creationDateTime;
			this.IsActive = isActive;
			this.tblMaterials_MaterialId = tblMaterials_MaterialId;
        }
    }
}
