//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-05-09 - 15:27:41
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblDocumentGroupDTO
    {
        [DataMember()]
        public Int32 DocumentGroupId { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "Please enter group name.")]
        public String GroupName { get; set; }

    }
}
