//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-12 - 20:08:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblEntityMasterDTO
    {
        [DataMember()]
        public Int32 EntityId { get; set; }

        [DataMember()]
        public String EntityName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public string ControllerName { get; set; }

        public tblEntityMasterDTO()
        {
        }

        public tblEntityMasterDTO(Int32 entityId, String entityName, String description)
        {
            this.EntityId = entityId;
            this.EntityName = entityName;
            this.Description = description;
        }
    }
}
