//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-17 - 14:19:52
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblImageMasterDTO
    {
        [DataMember()]
        public Int64 ImageID { get; set; }

        [DataMember()]
        public String ImagesPath { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "Comment is required")]
        public String Comment { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        public Nullable<int> DocumentGroupId { get; set; }

        public string DocumentGroupName { get; set; }

        public List<tblDocumentGroupDTO> DocumentGroupList { get; set; }

        public tblImageMasterDTO()
        {
        }

        public tblImageMasterDTO(Int64 imageID, String imagesPath, String comment, Nullable<Int32> createBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime)
        {
			this.ImageID = imageID;
			this.ImagesPath = imagesPath;
			this.Comment = comment;
			this.CreateBy = createBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
        }
    }
}
