//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/03/01 - 20:26:20
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblMaterialDTO
    {
        [DataMember()]
        public Int32 MaterialId { get; set; }

        [DataMember()]
        public Int32 MaterialGroupId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public Double BasicRate { get; set; }

        [DataMember()]
        public Double OpeningStock { get; set; }

        [DataMember()]
        public Int32 MemberId { get; set; }

        [DataMember()]
        public Int32 CompanyId { get; set; }

        [DataMember()]
        public DateTime CreationDateTime { get; set; }

        [DataMember()]
        public Int32 tblCompany_CompanyId { get; set; }

        [DataMember()]
        public Int32 tblMaterialGroup_MaterialGroupId { get; set; }

        [DataMember()]
        public Int32 tblMember_MemberId { get; set; }

        public tblMaterialDTO()
        {
        }

        public tblMaterialDTO(Int32 materialId, Int32 materialGroupId, String name, Double basicRate, Double openingStock, Int32 memberId, Int32 companyId, DateTime creationDateTime, Int32 tblCompany_CompanyId, Int32 tblMaterialGroup_MaterialGroupId, Int32 tblMember_MemberId)
        {
			this.MaterialId = materialId;
			this.MaterialGroupId = materialGroupId;
			this.Name = name;
			this.BasicRate = basicRate;
			this.OpeningStock = openingStock;
			this.MemberId = memberId;
			this.CompanyId = companyId;
			this.CreationDateTime = creationDateTime;
			this.tblCompany_CompanyId = tblCompany_CompanyId;
			this.tblMaterialGroup_MaterialGroupId = tblMaterialGroup_MaterialGroupId;
			this.tblMember_MemberId = tblMember_MemberId;
        }
    }
}
