//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/03/01 - 20:26:21
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblMaterialGroupDTO
    {
        [DataMember()]
        public Int32 MaterialGroupId { get; set; }

        [DataMember()]
        public String GroupName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public List<Int32> tblMaterials_MaterialId { get; set; }

        public tblMaterialGroupDTO()
        {
        }

        public tblMaterialGroupDTO(Int32 materialGroupId, String groupName, String description, List<Int32> tblMaterials_MaterialId)
        {
			this.MaterialGroupId = materialGroupId;
			this.GroupName = groupName;
			this.Description = description;
			this.tblMaterials_MaterialId = tblMaterials_MaterialId;
        }
    }
}
