//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/03/01 - 20:26:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblMemberPermissionDTO
    {
        [DataMember()]
        public Int32 MemberPermissionId { get; set; }

        [DataMember()]
        public Int32 PermisisonId { get; set; }

        [DataMember()]
        public Int32 MemberId { get; set; }

        [DataMember()]
        public Int32 tblMember_MemberId { get; set; }

        [DataMember()]
        public Int32 tblPermissionMaster_PermissionId { get; set; }

        public tblMemberPermissionDTO()
        {
        }

        public tblMemberPermissionDTO(Int32 memberPermissionId, Int32 permisisonId, Int32 memberId, Int32 tblMember_MemberId, Int32 tblPermissionMaster_PermissionId)
        {
			this.MemberPermissionId = memberPermissionId;
			this.PermisisonId = permisisonId;
			this.MemberId = memberId;
			this.tblMember_MemberId = tblMember_MemberId;
			this.tblPermissionMaster_PermissionId = tblPermissionMaster_PermissionId;
        }
    }
}
