//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/03/01 - 17:01:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblMemberDTO
    {
        [DataMember()]
        public Int32 MemberId { get; set; }

        [DataMember()]
        public Nullable<Int32> MemberTypeId { get; set; }

        [DataMember()]
        public String FirstName { get; set; }

        [DataMember()]
        public String LastName { get; set; }

        [DataMember()]
        public String EmailAddress { get; set; }

        [DataMember()]
        public String MobileNo { get; set; }

        [DataMember()]
        public String Password { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Int32 tblMemberType_MemberTypeId { get; set; }

        [DataMember()]
        public List<Int32> tblMemberPermissions_MemberPermissionId { get; set; }

        public tblMemberDTO()
        {
        }

        public tblMemberDTO(Int32 memberId, Nullable<Int32> memberTypeId, String firstName, String lastName, String emailAddress, String mobileNo, String password, Nullable<Boolean> isActive, Int32 tblMemberType_MemberTypeId, List<Int32> tblMemberPermissions_MemberPermissionId)
        {
			this.MemberId = memberId;
			this.MemberTypeId = memberTypeId;
			this.FirstName = firstName;
			this.LastName = lastName;
			this.EmailAddress = emailAddress;
			this.MobileNo = mobileNo;
			this.Password = password;
			this.IsActive = isActive;
			this.tblMemberType_MemberTypeId = tblMemberType_MemberTypeId;
			this.tblMemberPermissions_MemberPermissionId = tblMemberPermissions_MemberPermissionId;
        }
    }
}
