//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/03/01 - 17:01:50
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblMemberTypeDTO
    {
        [DataMember()]
        public Int32 MemberTypeId { get; set; }

        [DataMember()]
        public String TypeName { get; set; }

        [DataMember()]
        public List<Int32> tblMembers_MemberId { get; set; }

        public tblMemberTypeDTO()
        {
        }

        public tblMemberTypeDTO(Int32 memberTypeId, String typeName, List<Int32> tblMembers_MemberId)
        {
			this.MemberTypeId = memberTypeId;
			this.TypeName = typeName;
			this.tblMembers_MemberId = tblMembers_MemberId;
        }
    }
}
