//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-12 - 18:32:08
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblMemberDTO
    {
        public tblMemberDTO()
        {
            ProjectList = new List<tblProjectDTO>();
            EntityList = new List<tblEntityMasterDTO>();
            MemberPermissionList = new List<tblMemberPermissionDTO>();
            SelectedProject = new List<int>();
        }

        [DataMember()]
        public Int32 MemberId { get; set; }

        [DataMember()]
        public Int32 MemberTypeId { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "Please enter first name.")]
        public String FirstName { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "Please enter last name.")]
        public String LastName { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "Please enter address.")]
        public String Address { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "Please enter email address.")]
        public String EmailAddress { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "Please enter mobile no.")]
        public String MobileNo { get; set; }

        [DataMember()]
        [Required(ErrorMessage = "Please enter password.")]
        public String Password { get; set; }

        [DataMember()]
        public Boolean IsActive { get; set; }

        public static string ErrorMessage { get; set; }

        public static int StatuID { get; set; }

        public string MemberTypeString { get; set; }

        public bool RememberMe { get; set; }

        public List<tblProjectDTO> ProjectList { get; set; }

        public List<tblEntityMasterDTO> EntityList { get; set; }

        public List<tblMemberPermissionDTO> MemberPermissionList { get; set; }

        public string ProjectSelectionString { get; set; }

        public string EntityPermissionSelectionString { get; set; }

        public List<int> SelectedProject { get; set; }

    }
}
