//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-12 - 20:08:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblMemberPermissionDTO
    {
        [DataMember()]
        public Int32 MemberPermissionId { get; set; }

        [DataMember()]
        public Int32 ProjectId { get; set; }

        [DataMember()]
        public Int32 MemberId { get; set; }

        [DataMember()]
        public Int32 EnitytId { get; set; }

        [DataMember()]
        public Boolean CanListAll { get; set; }

        [DataMember()]
        public Boolean CanInsert { get; set; }

        [DataMember()]
        public Boolean CanEdit { get; set; }

        [DataMember()]
        public Boolean CanDelete { get; set; }

        public tblMemberPermissionDTO()
        {
        }

        public tblMemberPermissionDTO(Int32 memberPermissionId, Int32 projectId, Int32 memberId, Int32 enitytId, Boolean canListAll, Boolean canInsert, Boolean canEdit, Boolean canDelete)
        {
			this.MemberPermissionId = memberPermissionId;
			this.ProjectId = projectId;
			this.MemberId = memberId;
			this.EnitytId = enitytId;
			this.CanListAll = canListAll;
			this.CanInsert = canInsert;
			this.CanEdit = canEdit;
			this.CanDelete = canDelete;
        }
    }
}
