//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/03/01 - 20:26:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblPermissionMasterDTO
    {
        [DataMember()]
        public Int32 PermissionId { get; set; }

        [DataMember()]
        public String PermissionName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public List<Int32> tblMemberPermissions_MemberPermissionId { get; set; }

        public tblPermissionMasterDTO()
        {
        }

        public tblPermissionMasterDTO(Int32 permissionId, String permissionName, String description, List<Int32> tblMemberPermissions_MemberPermissionId)
        {
			this.PermissionId = permissionId;
			this.PermissionName = permissionName;
			this.Description = description;
			this.tblMemberPermissions_MemberPermissionId = tblMemberPermissions_MemberPermissionId;
        }
    }
}
