//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-12 - 20:08:20
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class tblProjectDTO
    {
        public int ProjectId { get; set; }
        public string Title { get; set; }
        public string SiteName { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public System.DateTime StratDateTime { get; set; }
        public string Catalog { get; set; }
        public bool IsActive { get; set; }
    }
}
