//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 14:09:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ProjectManagement.Domain
{
    [DataContract()]
    public partial class userDTO
    {
        [DataMember()]
        public String Uids { get; set; }

        [DataMember()]
        public String Passwords { get; set; }

        [DataMember()]
        public String Permit { get; set; }

        public userDTO()
        {
        }

        public userDTO(String uids, String passwords, String permit)
        {
			this.Uids = uids;
			this.Passwords = passwords;
			this.Permit = permit;
        }
    }
}
